(lang dune 3.20)

(name ultrac)

(generate_opam_files false)

(package
 (name ultrac)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))